In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('Mem-Map.csv')
pd.set_option('display.max_rows', None)

In [3]:
df

,Type,Start,End,# Pages,Attributes
0,Available,0000000000000000,0000000000086FFF,0000000000000087,000000000000000F
1,BS_Data,0000000000087000,0000000000087FFF,0000000000000001,000000000000000F
2,Available,0000000000088000,000000000009EFFF,0000000000000017,000000000000000F
3,Reserved,000000000009F000,000000000009FFFF,0000000000000001,000000000000000F
4,Available,0000000000100000,000000002AB3FFFF,000000000002AA40,000000000000000F
5,BS_Data,000000002AB40000,000000002ABBFFFF,0000000000000080,000000000000000F
6,Available,000000002ABC0000,0000000036AD3FFF,000000000000BF14,000000000000000F
7,BS_Data,0000000036AD4000,0000000036B22FFF,000000000000004F,000000000000000F
8,LoaderCode,0000000036B23000,0000000036C39FFF,0000000000000117,000000000000000F
9,Available,0000000036C3A000,0000000036C52FFF,0000000000000019,000000000000000F
10,BS_Data,0000000036C53000,0000000036C69FFF,0000000000000017,000000000000000F
11,Available,0000000036C6A000,0000000036C6AFFF,0000000000000001,000000000000000F
12,BS_Data,0000000036C6B000,000000003C8FEFFF,0000000000005C94,000000000000000F
13,BS_Code,000000003C8FF000,000000003C91AFFF,000000000000001C,000000000000000F
14,BS_Data,000000003C91B000,000000003C92BFFF,0000000000000011,000000000000000F
15,BS_Code,000000003C92C000,000000003C939FFF,000000000000000E,000000000000000F
16,BS_Data,000000003C93A000,000000003C957FFF,000000000000001E,000000000000000F
17,BS_Code,000000003C958000,000000003C95AFFF,0000000000000003,000000000000000F
18,BS_Data,000000003C95B000,000000003C96DFFF,0000000000000013,000000000000000F
19,BS_Code,000000003C96E000,000000003C96FFFF,0000000000000002,000000000000000F
20,BS_Data,000000003C970000,000000003C980FFF,0000000000000011,000000000000000F
21,BS_Code,000000003C981000,000000003C989FFF,0000000000000009,000000000000000F
22,BS_Data,000000003C98A000,000000003C996FFF,000000000000000D,000000000000000F
23,BS_Code,000000003C997000,000000003C9B3FFF,000000000000001D,000000000000000F
24,BS_Data,000000003C9B4000,000000003CA11FFF,000000000000005E,000000000000000F
25,BS_Code,000000003CA12000,000000003CA13FFF,0000000000000002,000000000000000F
26,BS_Data,000000003CA14000,000000003CA18FFF,0000000000000005,000000000000000F
27,BS_Code,000000003CA19000,000000003CA1AFFF,0000000000000002,000000000000000F
28,BS_Data,000000003CA1B000,000000003CA1FFFF,0000000000000005,000000000000000F
29,BS_Code,000000003CA20000,000000003CA23FFF,0000000000000004,000000000000000F
30,BS_Data,000000003CA24000,000000003CA2BFFF,0000000000000008,000000000000000F
31,BS_Code,000000003CA2C000,000000003CA2DFFF,0000000000000002,000000000000000F
32,BS_Data,000000003CA2E000,000000003CA33FFF,0000000000000006,000000000000000F
33,BS_Code,000000003CA34000,000000003CA34FFF,0000000000000001,000000000000000F
34,BS_Data,000000003CA35000,000000003CA53FFF,000000000000001F,000000000000000F
35,BS_Code,000000003CA54000,000000003CA57FFF,0000000000000004,000000000000000F
36,BS_Data,000000003CA58000,000000003CA5FFFF,0000000000000008,000000000000000F
37,BS_Code,000000003CA60000,000000003CA64FFF,0000000000000005,000000000000000F
38,BS_Data,000000003CA65000,000000003CB24FFF,00000000000000C0,000000000000000F
39,BS_Code,000000003CB25000,000000003CB66FFF,0000000000000042,000000000000000F
40,BS_Data,000000003CB67000,000000003CBA4FFF,000000000000003E,000000000000000F
41,BS_Code,000000003CBA5000,000000003CBA6FFF,0000000000000002,000000000000000F
42,BS_Data,000000003CBA7000,000000003CBB8FFF,0000000000000012,000000000000000F
43,BS_Code,000000003CBB9000,000000003CBD6FFF,000000000000001E,000000000000000F
44,BS_Data,000000003CBD7000,000000003CCCEFFF,00000000000000F8,000000000000000F
45,BS_Code,000000003CCCF000,000000003CCD5FFF,0000000000000007,000000000000000F
46,BS_Data,000000003CCD6000,000000003CCE0FFF,000000000000000B,000000000000000F
47,BS_Code,000000003CCE1000,000000003CCE5FFF,0000000000000005,000000000000000F
48,BS_Data,000000003CCE6000,000000003F1EFFFF,000000000000250A,000000000000000F
49,BS_Code,000000003F1F0000,000000003F20AFFF,000000000000001B,000000000000000F
50,BS_Data,000000003F20B000,000000003F20CFFF,0000000000000002,000000000000000F
51,BS_Code,000000003F20D000,000000003F217FFF,000000000000000B,000000000000000F
52,BS_Data,000000003F218000,000000003F228FFF,0000000000000011,000000000000000F
53,Reserved,000000003F229000,000000003FB28FFF,0000000000000900,000000000000000F
54,BS_Code,000000003FB29000,000000003FB2FFFF,0000000000000007,000000000000000F
55,BS_Data,000000003FB30000,000000003FB3EFFF,000000000000000F,000000000000000F
56,Available,000000003FB3F000,00000000401CDFFF,000000000000068F,000000000000000F
57,BS_Code,00000000401CE000,000000004193EFFF,0000000000001771,000000000000000F
58,RT_Code,000000004193F000,0000000041D0EFFF,00000000000003D0,800000000000000F
59,RT_Data,0000000041D0F000,00000000429DEFFF,0000000000000CD0,800000000000000F
60,Reserved,00000000429DF000,00000000439DEFFF,0000000000001000,000000000000000F
61,ACPI_NVS,00000000439DF000,000000004698EFFF,0000000000002FB0,000000000000000F
62,ACPI_Recl,000000004698F000,0000000046AFEFFF,0000000000000170,000000000000000F
63,BS_Data,0000000046AFF000,0000000046AFFFFF,0000000000000001,000000000000000F
64,RT_Data,0000000046B00000,0000000046FFFFFF,0000000000000500,800000000000000F
65,Available,0000000100000000,00000004AD7FFFFF,00000000003AD800,000000000000000F
66,Reserved,00000000000A0000,00000000000FFFFF,0000000000000060,0000000000000000
67,Reserved,0000000047000000,000000004AFFFFFF,0000000000004000,000000000000000F
68,Reserved,000000004B400000,000000004B5FFFFF,0000000000000200,000000000000000F
69,Reserved,000000004C000000,000000004DFFFFFF,0000000000002000,0000000000000009
70,Reserved,000000004E000000,00000000527FFFFF,0000000000004800,0000000000000000
71,MMIO,00000000C0000000,00000000CFFFFFFF,0000000000010000,8000000000000001
72,Reserved,00000000FED20000,00000000FED7FFFF,0000000000000060,0000000000000000
73,MMIO,00000000FF000000,00000000FFFFFFFF,0000000000010000,8000000000000001

In [4]:
df = df.sort_values(by = 'Start')

In [5]:
df

,Type,Start,End,# Pages,Attributes
0,Available,0000000000000000,0000000000086FFF,0000000000000087,000000000000000F
1,BS_Data,0000000000087000,0000000000087FFF,0000000000000001,000000000000000F
2,Available,0000000000088000,000000000009EFFF,0000000000000017,000000000000000F
3,Reserved,000000000009F000,000000000009FFFF,0000000000000001,000000000000000F
66,Reserved,00000000000A0000,00000000000FFFFF,0000000000000060,0000000000000000
4,Available,0000000000100000,000000002AB3FFFF,000000000002AA40,000000000000000F
5,BS_Data,000000002AB40000,000000002ABBFFFF,0000000000000080,000000000000000F
6,Available,000000002ABC0000,0000000036AD3FFF,000000000000BF14,000000000000000F
7,BS_Data,0000000036AD4000,0000000036B22FFF,000000000000004F,000000000000000F
8,LoaderCode,0000000036B23000,0000000036C39FFF,0000000000000117,000000000000000F
9,Available,0000000036C3A000,0000000036C52FFF,0000000000000019,000000000000000F
10,BS_Data,0000000036C53000,0000000036C69FFF,0000000000000017,000000000000000F
11,Available,0000000036C6A000,0000000036C6AFFF,0000000000000001,000000000000000F
12,BS_Data,0000000036C6B000,000000003C8FEFFF,0000000000005C94,000000000000000F
13,BS_Code,000000003C8FF000,000000003C91AFFF,000000000000001C,000000000000000F
14,BS_Data,000000003C91B000,000000003C92BFFF,0000000000000011,000000000000000F
15,BS_Code,000000003C92C000,000000003C939FFF,000000000000000E,000000000000000F
16,BS_Data,000000003C93A000,000000003C957FFF,000000000000001E,000000000000000F
17,BS_Code,000000003C958000,000000003C95AFFF,0000000000000003,000000000000000F
18,BS_Data,000000003C95B000,000000003C96DFFF,0000000000000013,000000000000000F
19,BS_Code,000000003C96E000,000000003C96FFFF,0000000000000002,000000000000000F
20,BS_Data,000000003C970000,000000003C980FFF,0000000000000011,000000000000000F
21,BS_Code,000000003C981000,000000003C989FFF,0000000000000009,000000000000000F
22,BS_Data,000000003C98A000,000000003C996FFF,000000000000000D,000000000000000F
23,BS_Code,000000003C997000,000000003C9B3FFF,000000000000001D,000000000000000F
24,BS_Data,000000003C9B4000,000000003CA11FFF,000000000000005E,000000000000000F
25,BS_Code,000000003CA12000,000000003CA13FFF,0000000000000002,000000000000000F
26,BS_Data,000000003CA14000,000000003CA18FFF,0000000000000005,000000000000000F
27,BS_Code,000000003CA19000,000000003CA1AFFF,0000000000000002,000000000000000F
28,BS_Data,000000003CA1B000,000000003CA1FFFF,0000000000000005,000000000000000F
29,BS_Code,000000003CA20000,000000003CA23FFF,0000000000000004,000000000000000F
30,BS_Data,000000003CA24000,000000003CA2BFFF,0000000000000008,000000000000000F
31,BS_Code,000000003CA2C000,000000003CA2DFFF,0000000000000002,000000000000000F
32,BS_Data,000000003CA2E000,000000003CA33FFF,0000000000000006,000000000000000F
33,BS_Code,000000003CA34000,000000003CA34FFF,0000000000000001,000000000000000F
34,BS_Data,000000003CA35000,000000003CA53FFF,000000000000001F,000000000000000F
35,BS_Code,000000003CA54000,000000003CA57FFF,0000000000000004,000000000000000F
36,BS_Data,000000003CA58000,000000003CA5FFFF,0000000000000008,000000000000000F
37,BS_Code,000000003CA60000,000000003CA64FFF,0000000000000005,000000000000000F
38,BS_Data,000000003CA65000,000000003CB24FFF,00000000000000C0,000000000000000F
39,BS_Code,000000003CB25000,000000003CB66FFF,0000000000000042,000000000000000F
40,BS_Data,000000003CB67000,000000003CBA4FFF,000000000000003E,000000000000000F
41,BS_Code,000000003CBA5000,000000003CBA6FFF,0000000000000002,000000000000000F
42,BS_Data,000000003CBA7000,000000003CBB8FFF,0000000000000012,000000000000000F
43,BS_Code,000000003CBB9000,000000003CBD6FFF,000000000000001E,000000000000000F
44,BS_Data,000000003CBD7000,000000003CCCEFFF,00000000000000F8,000000000000000F
45,BS_Code,000000003CCCF000,000000003CCD5FFF,0000000000000007,000000000000000F
46,BS_Data,000000003CCD6000,000000003CCE0FFF,000000000000000B,000000000000000F
47,BS_Code,000000003CCE1000,000000003CCE5FFF,0000000000000005,000000000000000F
48,BS_Data,000000003CCE6000,000000003F1EFFFF,000000000000250A,000000000000000F
49,BS_Code,000000003F1F0000,000000003F20AFFF,000000000000001B,000000000000000F
50,BS_Data,000000003F20B000,000000003F20CFFF,0000000000000002,000000000000000F
51,BS_Code,000000003F20D000,000000003F217FFF,000000000000000B,000000000000000F
52,BS_Data,000000003F218000,000000003F228FFF,0000000000000011,000000000000000F
53,Reserved,000000003F229000,000000003FB28FFF,0000000000000900,000000000000000F
54,BS_Code,000000003FB29000,000000003FB2FFFF,0000000000000007,000000000000000F
55,BS_Data,000000003FB30000,000000003FB3EFFF,000000000000000F,000000000000000F
56,Available,000000003FB3F000,00000000401CDFFF,000000000000068F,000000000000000F
57,BS_Code,00000000401CE000,000000004193EFFF,0000000000001771,000000000000000F
58,RT_Code,000000004193F000,0000000041D0EFFF,00000000000003D0,800000000000000F
59,RT_Data,0000000041D0F000,00000000429DEFFF,0000000000000CD0,800000000000000F
60,Reserved,00000000429DF000,00000000439DEFFF,0000000000001000,000000000000000F
61,ACPI_NVS,00000000439DF000,000000004698EFFF,0000000000002FB0,000000000000000F
62,ACPI_Recl,000000004698F000,0000000046AFEFFF,0000000000000170,000000000000000F
63,BS_Data,0000000046AFF000,0000000046AFFFFF,0000000000000001,000000000000000F
64,RT_Data,0000000046B00000,0000000046FFFFFF,0000000000000500,800000000000000F
67,Reserved,0000000047000000,000000004AFFFFFF,0000000000004000,000000000000000F
68,Reserved,000000004B400000,000000004B5FFFFF,0000000000000200,000000000000000F
69,Reserved,000000004C000000,000000004DFFFFFF,0000000000002000,0000000000000009
70,Reserved,000000004E000000,00000000527FFFFF,0000000000004800,0000000000000000
71,MMIO,00000000C0000000,00000000CFFFFFFF,0000000000010000,8000000000000001
72,Reserved,00000000FED20000,00000000FED7FFFF,0000000000000060,0000000000000000
73,MMIO,00000000FF000000,00000000FFFFFFFF,0000000000010000,8000000000000001
65,Available,0000000100000000,00000004AD7FFFFF,00000000003AD800,000000000000000F

In [6]:
df.to_csv('Mem-Map-Asc.csv', index = False)